name = "StaTech Industry"
author = "static"
version = "1.1.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef184a72041f66b54ba613416ee1929b7ccaffb2d20cc60f45f69db4e2e2e4bd"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
